module.exports = {
    rules: {
        'indent': ['error', 4, {'SwitchCase': 1}],
        'no-var': 'off',
        'no-param-reassign': 'off',
        'space-before-function-paren': ['error', 'never'],
        'comma-dangle': ['error', 'never'],
        'consistent-return': 'off',
        'func-names': 'off',
        'no-shadow': 'off',
        'vars-on-top': 'off',
        'arrow-parens': 'off',
        'eol-last': ['error', 'always'],
        'prefer-arrow-callback': 'off',
        'no-use-before-define': 'off',
        'eqeqeq': 'off',
        'curly': ['warn', 'multi-line'],
        'no-underscore-dangle': [2, {allowAfterThis: true, allow: ['_instance', '__']}],
        'no-unused-expressions': ['error', {'allowShortCircuit': true, 'allowTernary': true}],
        'max-len': ['error', 120],
        'guard-for-in': 'off',
        'no-restricted-syntax': 'off',
        'dot-notation': 'off',
        'no-return-assign': 'off',
        'no-mixed-operators': 'off',
        'default-case': 'warn',
        'spaced-comment': 'off',
        'no-continue': 'off',
        'no-plusplus': 'off',
        'one-var': ['error', {'initialized': 'never'}],
        'one-var-declaration-per-line': ['error', 'initializations'],
        'no-extend-native': ['error', {'exceptions': ['Error']}],
        'new-cap': 'off',
        'quote-props': ['error', 'consistent'],
        'no-multi-assign': 'off',
        'prefer-const': 'off',
        'class-methods-use-this': 'off',
        'no-alert': 'off',
        'no-nested-ternary': 'off',
        'quotes': ['error', 'single', {'allowTemplateLiterals': true}],
        'no-empty': ['error', {'allowEmptyCatch': true}],
        'no-confusing-arrow': 'off',
        'import/extensions': ['error', 'always', {
          js: 'never'
        }],
        'import/no-extraneous-dependencies': ['error', { optionalDependencies: false }]
    }
};
